services:
  itarazzo-client:
    # image: leidenheit/itarazzo-client:latest
    build:
      context: .
    stop_grace_period: 90s
    environment:
      - ARAZZO_FILE=/itarazzo/resources/pet-store.arazzo.yaml
      - ARAZZO_INPUTS_FILE=/itarazzo/resources/arazzo-inputs.json
    volumes:
      - ./src/test/resources:/itarazzo/resources
      - ./target/reports:/itarazzo/target/reports
